[book]
authors = ["lancerstadium"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Rust Lab"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/lancerstadium/"
git-repository-icon = "fa-github"

